Repository junhok82/Algorithm_study, pull requests merged in 2019-12, with the labels that each got.

#18 [KJH BOJ 2579] Solving & Alternative
  DP/BOJ_2579/KJH_Bottom_up.cpp
  DP/BOJ_2579/KJH_Top_Down.cpp
Labels: alternative, solving

#20 [KMJ BOJ 2579] Solving
  DP/BOJ_2579/KMJ_2579.cpp
Labels: solving

#19 [SSK BOJ 2579] Solving & Alternative
  DP/BOJ_2579/SSK.c
Labels: solving

#17 [MBC BOJ 2579] Solving & Alternative
  DP/BOJ_2579/2579_ClimbingStair.cpp
  DP/BOJ_2579/2579_ClimbingStair2.cpp
Labels: alternative, solving

#24 [SSK BOJ 1912] Solving & Alternative
  DP/BOJ_1912/SSK_1912.cpp
Labels: solving

#25 [SSK BOJ 1806] Solving (update)
  DP/BOJ_1806/SSK.cpp
Labels: solving

#26 [MBC BOJ 1912] Solving & Alternative solving
  DP/BOJ_1806/MBC_BOJ_1806__ver1.cpp
  DP/BOJ_1806/MBC_BOJ_1806__ver2.cpp
  DP/BOJ_1912/MBC_BOJ_1912_ver1.cpp
  DP/BOJ_1912/MBC_BOJ_1912_ver2.cpp
Labels: alternative, solving

#27 [MBC BOJ 1806] Solving & Alternative solving
  DP/BOJ_1806/MBC_BOJ_1806_ver1.cpp
  DP/BOJ_1806/MBC_BOJ_1806_ver2.cpp
Labels: alternative, solving

#29 [KJH BOJ 1912] Solving & Alternative solving
  DP/BOJ_1912/KJH.cpp
  DP/BOJ_1912/KJH_split.cpp
Labels: alternative, solving

#30 [KJH BOJ 1806] Solving & Alternative solving
  DP/BOJ_1806/KJH.cpp
  DP/BOJ_1806/KJH_Two_Point.cpp
Labels: alternative, solving

#31 [KJH BOJ 2294] Solving & Alternative solving
  DP/BOJ_2294/KJH.cpp
  DP/BOJ_2294/KJH_Top_down.cpp
Labels: alternative, solving

#32 [SSK_BOJ_2294] Solving & Alternative
  DP/BOJ_2294/SSK.cpp
  DP/BOJ_2294/SSK_alter.cpp
Labels: alternative, solving

#39 [MBC_BOJ_2294] Solving & Alternative
  DP/BOJ_2294/MBC_BOJ_2294.cpp
Labels: alternative :heavy_plus_sign:, solving :key:

#47 [KJH_BOJ_11724] Solving
  DFS/BOJ_11724/KJH.cpp
Labels: solving :key:

#57 [MBC_BOJ_2667] Solving & Alternative
  DFS/BOJ_2667/MBC_BOJ_2667.cpp
Labels: alternative :heavy_plus_sign:

#56 [MBC_BOJ_1012] Solving & Alternative
  DFS/BOJ_1012/MBC_BOJ_1012.cpp
Labels: alternative :heavy_plus_sign:

#55 [MBC_BOJ_1743] Solving & Alternative
  DFS/BOJ_1743/MBC_BOJ_1743.cpp
Labels: alternative :heavy_plus_sign:

#54 [MBC_BOJ_11724] Solving & Alternative
  DFS/BOJ_11724/MBC_BOJ_11724.cpp
  DP/BOJ_12865/MBC_BOJ_12865.cpp
Labels: alternative :heavy_plus_sign:

#53 [SSK_BOJ_2667] Solving &Alternaive
  DFS/BOJ_2667/SSK.cpp
Labels: alternative :heavy_plus_sign:, solving :key:

#52 [SSK_BOJ_1743] Solving &Alternaive
  DFS/BOJ_1743/SSK.cpp
Labels: alternative :heavy_plus_sign:, solving :key:

#51 [SSK_BOJ_11724]Solving &Alternative
  DFS/BOJ_11724/SSK.cpp
Labels: alternative :heavy_plus_sign:, solving :key:

#50 [SSK_BOJ_1012] Solving &Alternaive
  DFS/BOJ_1012/SSK.cpp
  DFS/BOJ_1012/SSK2.cpp
Labels: alternative :heavy_plus_sign:, solving :key:

#48 [KJH_BOJ_2667] Solving
  DFS/BOJ_2667/KJH.cpp
Labels: solving :key:
