Repository junhok82/Algorithm_study, pull requests merged in 2020-01, with the labels that each got.

#60 [SSK_7]Solving & Alternative
  DFS/BOJ_11403/SSK.cpp
  DFS/BOJ_9466/SSK(fail).cpp
  DFS/BOJ_9466/SSK.cpp
  DFS/PROGRAMMERS_49994/SSK_1.cpp
  DFS/PROGRAMMERS_49994/SSK_2.cpp
Labels: alternative :heavy_plus_sign:, solving :key:

#61 [MBC_7] Solving & Alternative
  DFS/BOJ_11403/MBC_BOJ_11403.cpp
  DFS/BOJ_9466/MBC_BOJ_9466_ver1.cpp
  DFS/BOJ_9466/MBC_BOJ_9466_ver2.cpp
  DFS/PROGRAMMERS_49994/MBC_PROGRAMMERS_49994.cpp
Labels: alternative :heavy_plus_sign:

#62 [KJH_7] Solving
  DFS/BOJ_11403/KJH.cpp
  DFS/BOJ_9466/KJH.cpp
  DFS/PROGRAMMERS_49994/KJH.cpp
Labels: solving :key:
